# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_auto_20171115_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='titulo',
            field=models.CharField(default='teste', max_length=50),
        ),
    ]
