# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0003_fotos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
